apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: provider
  name: provider
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: provider
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
      - env:
        - name: ARTIFACTS_PATH
          value: /provider/artifacts/
        - name: NETWORK_URL
          value: http://172.31.31.183:8545
        - name: PROVIDER_PRIVATE_KEY
          value: "PROVIDER_PRIVATEKEY"
        - name: LOG_LEVEL
          value: DEBUG
        - name: NETWORK_NAME
          value: gaiaxtestnet
        - name: OCEAN_PROVIDER_URL
          value: https://0.0.0.0:8030
        - name: OCEAN_PROVIDER_WORKERS
          value: "2"
        - name: OCEAN_PROVIDER_TIMEOUT
          value: "9000"
        - name: AQUARIUS_URL
          value: aquarius.ocean.svc.cluster.local:5000
        - name: PROVIDER_ADDRESS
          value: "PROVIDER_ADDRESS_KEY" 
        - name: OPERATOR_SERVICE_URL
          value: operator-api.ocean-operator.svc.cluster.local:8050
        image: oceanprotocol/provider-py:latest
        imagePullPolicy: Always
        name: provider
        ports:
        - containerPort: 8030
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
