apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: ocean
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: 'FF5z5&#5t9#L*4'
  POSTGRES_HOST: postgres.ocean-operator.svc.cluster.local
  POSTGRES_PORT: "5432"
