apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: ocean
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: J$ktE4LU^9Tk9!
  POSTGRES_HOST: postgres.ocean-operator.svc.cluster.local
  POSTGRES_PORT: "5432"
